/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.DBConnection;
import control.UIController;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Ailer
 */
public class Login extends javax.swing.JFrame {
    private final List<Component> toPrincipalColor;
    private final List<Component> componentTrees = new ArrayList<>();
    private boolean isDarkMode = true;
    private DBConnection connection;
    /**
     * Creates new form Login
     */
    public Login(){
        UIController.setEN();
        initComponents();
        connection = new DBConnection();
        toPrincipalColor = Arrays.asList(pLogin, pOthersConfig, pOthersAbout);
        setLocationRelativeTo(null);
        
        UIController.setLookAndFeel(this,"Nimbus");
        UIController.setOnlyNumber(textID, 9);   
        UIController.firstSetMode(isDarkMode, toPrincipalColor, new ArrayList(), this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        othersAbout = new javax.swing.JDialog();
        pOthersAbout = new javax.swing.JPanel();
        othersBClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        othersConfig = new javax.swing.JDialog();
        pOthersConfig = new javax.swing.JPanel();
        bGuardarConf = new javax.swing.JButton();
        labTemas = new javax.swing.JLabel();
        temas = new java.awt.Choice();
        pLogin = new javax.swing.JPanel();
        textPassword = new javax.swing.JPasswordField();
        textID = new javax.swing.JTextField();
        lUser = new javax.swing.JLabel();
        lPassword = new javax.swing.JLabel();
        bLogin = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuOtros = new javax.swing.JMenu();
        menuOtrosConfig = new javax.swing.JMenuItem();
        menuOtrosAbout = new javax.swing.JMenuItem();

        othersAbout.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        othersAbout.setTitle("Research - About");
        othersAbout.setFocusable(false);
        othersAbout.setMinimumSize(null);
        othersAbout.setResizable(false);
        othersAbout.setSize(new java.awt.Dimension(340, 260));
        othersAbout.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                othersAboutWindowClosed(evt);
            }
        });
        othersAbout.getContentPane().setLayout(new javax.swing.BoxLayout(othersAbout.getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        othersBClose.setText("Close");
        othersBClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                othersBCloseActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Group Members:\n        Alvarado Aguero Ailer Josue\n        Arce Vargas Armando Andres\n        Ávila Ramírez Paublo Alexander\n        Martinez Rivera German Josue\n\nDatabase:\n        Oracle NoSQL\n                                                                                2023");
        jTextArea1.setBorder(null);
        jTextArea1.setFocusable(false);
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout pOthersAboutLayout = new javax.swing.GroupLayout(pOthersAbout);
        pOthersAbout.setLayout(pOthersAboutLayout);
        pOthersAboutLayout.setHorizontalGroup(
            pOthersAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOthersAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pOthersAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pOthersAboutLayout.createSequentialGroup()
                        .addGap(0, 310, Short.MAX_VALUE)
                        .addComponent(othersBClose))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        pOthersAboutLayout.setVerticalGroup(
            pOthersAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pOthersAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(othersBClose)
                .addContainerGap())
        );

        othersAbout.getContentPane().add(pOthersAbout);

        othersConfig.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        othersConfig.setTitle("Research - Configuration");
        othersConfig.setMinimumSize(new java.awt.Dimension(230, 200));
        othersConfig.setResizable(false);
        othersConfig.setSize(new java.awt.Dimension(240, 200));
        othersConfig.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                othersConfigWindowClosed(evt);
            }
        });
        othersConfig.getContentPane().setLayout(new javax.swing.BoxLayout(othersConfig.getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        bGuardarConf.setText("Apply");
        bGuardarConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarConfActionPerformed(evt);
            }
        });

        labTemas.setText("Theme");

        temas.add("DarkMode");
        temas.add("LightMode");
        temas.setName(""); // NOI18N

        javax.swing.GroupLayout pOthersConfigLayout = new javax.swing.GroupLayout(pOthersConfig);
        pOthersConfig.setLayout(pOthersConfigLayout);
        pOthersConfigLayout.setHorizontalGroup(
            pOthersConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOthersConfigLayout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addComponent(bGuardarConf)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pOthersConfigLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labTemas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(temas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        pOthersConfigLayout.setVerticalGroup(
            pOthersConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pOthersConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pOthersConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(temas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labTemas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(bGuardarConf)
                .addContainerGap())
        );

        othersConfig.getContentPane().add(pOthersConfig);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Research - Login");
        setResizable(false);

        lUser.setText("User");

        lPassword.setText("Password");

        bLogin.setText("Login");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pLoginLayout = new javax.swing.GroupLayout(pLogin);
        pLogin.setLayout(pLoginLayout);
        pLoginLayout.setHorizontalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lPassword)
                    .addComponent(lUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(textID)
                    .addComponent(textPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        pLoginLayout.setVerticalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bLogin)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        menuOtros.setText("Others");

        menuOtrosConfig.setText("Configuration");
        menuOtrosConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOtrosConfigActionPerformed(evt);
            }
        });
        menuOtros.add(menuOtrosConfig);

        menuOtrosAbout.setText("About");
        menuOtrosAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOtrosAboutActionPerformed(evt);
            }
        });
        menuOtros.add(menuOtrosAbout);

        menuBar.add(menuOtros);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        String id = textID.getText();
        int personID = Integer.parseInt(id);
        boolean personExist = connection.getPerson(personID) != null;
        if ("66".equals(textID.getText()) && "66".equals(textPassword.getText())){
            this.dispose();
            AdminGUI adminGUI = new AdminGUI(isDarkMode, connection);
            adminGUI.setVisible(true);
        } else if ("99".equals(textID.getText()) && "99".equals(textPassword.getText())){
            this.dispose();
            UserGUI userGUI = new UserGUI(isDarkMode, connection);
            userGUI.setVisible(true);
        } else if (personExist && id.equals(textPassword.getText())){
            this.dispose();
            UserGUI userGUI = new UserGUI(isDarkMode, connection);
            userGUI.setVisible(true);
        } else {
            Color tColor = isDarkMode ? new Color(32, 32, 32) : new Color(255, 255, 255);
            JDialog dialog = UIController.makeDialog("Invalid ID or password.", tColor, JOptionPane.ERROR_MESSAGE, "Error");
            dialog.setVisible(true);      
        }
    }//GEN-LAST:event_bLoginActionPerformed

    private void menuOtrosConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOtrosConfigActionPerformed
        setEnabled(false);
        UIController.centerDialog(othersConfig);
        othersConfig.setVisible(true);
        othersConfig.setEnabled(true);
    }//GEN-LAST:event_menuOtrosConfigActionPerformed

    private void menuOtrosAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOtrosAboutActionPerformed
        setEnabled(false);
        UIController.centerDialog(othersAbout);
        othersAbout.setVisible(true);
        othersAbout.setEnabled(true);
    }//GEN-LAST:event_menuOtrosAboutActionPerformed

    private void othersBCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_othersBCloseActionPerformed
        UIController.focusMainGUI(this);
        othersAbout.dispose();
    }//GEN-LAST:event_othersBCloseActionPerformed

    private void othersAboutWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_othersAboutWindowClosed
        UIController.focusMainGUI(this);
        othersAbout.dispose();
    }//GEN-LAST:event_othersAboutWindowClosed

    private void bGuardarConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarConfActionPerformed
        UIController.focusMainGUI(this);
        if ("DarkMode".equals(temas.getSelectedItem())){
            UIController.setDarkMode(toPrincipalColor, componentTrees, this);
            isDarkMode = true;
        } else {
            UIController.setLightMode(toPrincipalColor, componentTrees, this);
            isDarkMode = false;
        }
        othersConfig.dispose();
    }//GEN-LAST:event_bGuardarConfActionPerformed

    private void othersConfigWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_othersConfigWindowClosed
        UIController.focusMainGUI(this);
        othersConfig.dispose();
    }//GEN-LAST:event_othersConfigWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGuardarConf;
    private javax.swing.JButton bLogin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel lUser;
    private javax.swing.JLabel labTemas;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuOtros;
    private javax.swing.JMenuItem menuOtrosAbout;
    private javax.swing.JMenuItem menuOtrosConfig;
    private javax.swing.JDialog othersAbout;
    private javax.swing.JButton othersBClose;
    private javax.swing.JDialog othersConfig;
    private javax.swing.JPanel pLogin;
    private javax.swing.JPanel pOthersAbout;
    private javax.swing.JPanel pOthersConfig;
    private java.awt.Choice temas;
    private javax.swing.JTextField textID;
    private javax.swing.JPasswordField textPassword;
    // End of variables declaration//GEN-END:variables
}
